### ISSUE TITLE
using -f for kubernetes doesn't work

### ISSUE THREAD

**Issue by oshadmon** [AnyLog-co/deployments#3]
**Branch**: os-dev

**Steps**: 
1. Clone os-dev branch in deployments repo  
```git clone -b os-dev https://github.com/AnyLog-co/deploymnets```

2. Switch to your own branch 
```cd  deploymnets ; git checkout -b rs-dev```

3. Package helm/remote-cli
```helm package helm/remote-cli```

4. deploy Remote-CLI
```helm install remote-cli-1.0.0.tgz --generate-name```

**Check Point**: When doing `kubectl get all` you'll see that the Remote CLI is running and configured against port 31800 

5. Stop Remote-CLI
```
helm delete `helm list | grep remote | awk -F " " '{print $1}'` 
``` 

6. Create new values.yaml file 
a) Copy `helm/values/remote-cli.yaml` to `helm/values/values.yaml`
```
cp  helm/values/remote-cli.yaml helm/values/values.yaml
```
b) Update line 26 - `port` value 
```
# before
port: 31800

# after
port: 31900
```

8. Start Remote-CLI wtth new YAML file
```helm install remote-cli-1.0.0.tgz --generate-name -f helm/values/values.yam```

**Expect**: When doing `kubectl get all` you'll see that the Remote CLI is running and configured against port 31900 
**Actual**: When doing `kubectl get all` you'll see that the Remote CLI is running and configured against port 31800

**Comment by royshadmon** [comment]
For step 8, try:

helm upgrade --reuse-values -f helm/values/values.yaml [chart-name]

**Comment by royshadmon** [comment]
https://stackoverflow.com/questions/52634741/how-do-i-upgrade-a-helm-chart-with-a-new-values-yaml-and-keep-the-previous-deplo

**Comment by oshadmon** [comment]
Resolution: https://stackoverflow.com/questions/51097553/can-i-have-multiple-values-yaml-files-for-helm#:~:text=Yes%2C%20it%27s%20possible%20to%20have%20multiple%20values%20files,also%20pass%20in%20a%20single%20value%20using%20--set.

```
# Generic command
helm install --values ${VALUE_FILE} [package-name] --generate-name

# Example:
helm install --values values/values.yaml remote-cli-1.0.0.tgz --generate-name 
```
